# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend
#   namespace: expense
# data:
#   DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  # these labels are deployments related lables
  labels:
    component: frontend
    project: expense 
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
      project: expense 
      tier: web
      # pod definition
  template:
    metadata:
      labels:
        component: frontend
        project: expense 
        tier: web
    spec:
      containers:
      - name: frontend
        image: gumma4545/frontend:v1.0
        # envFrom:
        # - configMapRef:
        #     name: frontend
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: expense 
    tier: web
  ports:
  - protocol: TCP
    port: 80 # service-port
    targetPort: 80  # target-port
